import { describe, test, expect } from 'bun:test';
import { mkdtempSync, rmSync, readFileSync, unlinkSync, copyFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { DurableJournal, canonicalContext, digest, loadDurableKey, type DurableRunSpec } from './index.ts';
import { DURABLE_RUNTIME_MANIFEST } from '../protocol/durable-execution.ts';
const roots: string[] = [];
function fixture() { const root = mkdtempSync(join(tmpdir(),'artist-journal-')); roots.push(root); const key=randomBytes(32); return {root,key,journal:new DurableJournal({configRoot:root,key})}; }
function spec(): DurableRunSpec { return {credentialIdentity:'a'.repeat(64),runtimeManifest:{...DURABLE_RUNTIME_MANIFEST},engine:'sqlite-v2-readonly-1',runId:'run',workspaceId:'workspace',createdAt:Date.now(),allowedTools:['read'],model:'fixture',maxOutputTokens:100,commandId:'command',authority:{secret:'SECRET-AUTHORITY'},context:{prompt:'SECRET-PROMPT'},deadlineAt:Date.now()+100000,maxModelAttempts:4,costPolicy:{unit:'verified-free',maxTotalUnits:0,maxUnitsPerAttempt:0}}; }
const context = {messages:[{role:'user',content:'hello',timestamp:1}]};
const message = {role:'assistant',content:[{type:'toolCall',id:'call',name:'read',arguments:{path:'x'}}],stopReason:'toolUse'};
const final = {role:'assistant',content:[{type:'text',text:'SECRET-RESULT'}],stopReason:'stop'};
describe('production durable journal',()=>{
 test('commits ordered model/tool results and replays exact immutable values after restart',async()=>{ const f=fixture(); f.journal.admit(spec()); let claim=f.journal.claim('run','workspace'); let bridge=f.journal.bridge(claim); await bridge.checkpoint({kind:'model-start',turn:0,context}); await bridge.checkpoint({kind:'model-result',turn:0,message}); await bridge.checkpoint({kind:'tool-start',turn:0,callId:'call',tool:'read',input:{path:'/normalized/x'}}); await bridge.checkpoint({kind:'tool-result',turn:0,callId:'call',result:{content:'SECRET-FILE'}}); f.journal.release(claim); f.journal.close(); const j=new DurableJournal({configRoot:f.root,key:f.key}); claim=j.claim('run','workspace'); bridge=j.bridge(claim); expect((await bridge.checkpoint({kind:'model-start',turn:0,context:{messages:[{role:'user',content:'hello',timestamp:9}]}})).cached).toEqual(message); expect((await bridge.checkpoint({kind:'tool-start',turn:0,callId:'call',tool:'read',input:{path:'/normalized/x'}})).cached).toEqual({content:'SECRET-FILE'}); await expect(bridge.checkpoint({kind:'tool-start',turn:0,callId:'call',tool:'read',input:{path:'different'}})).rejects.toThrow('input-changed'); await bridge.checkpoint({kind:'model-start',turn:1,context}); await bridge.checkpoint({kind:'model-result',turn:1,message:final}); await bridge.checkpoint({kind:'complete'}); expect(j.get('run','workspace').status).toBe('succeeded'); expect(j.events('run','workspace').length).toBe(8); j.close(); expect(readFileSync(join(f.root,'durable-execution/journal.sqlite')).includes(Buffer.from('SECRET-'))).toBe(false); });
 test('context normalization preserves timestamps inside tool data',()=>{expect(digest(canonicalContext({messages:[{role:'toolResult',timestamp:1,content:{timestamp:5}}]}))).not.toBe(digest(canonicalContext({messages:[{role:'toolResult',timestamp:1,content:{timestamp:6}}]})));});
 test('unknown tools and incomplete predecessors stop before successor',async()=>{const f=fixture(); f.journal.admit(spec());const b=f.journal.bridge(f.journal.claim('run','workspace')); await b.checkpoint({kind:'model-start',turn:0,context}); await expect(b.checkpoint({kind:'model-result',turn:0,message:{...message,content:[{type:'toolCall',id:'bad',name:'bash',arguments:{}}]}})).rejects.toThrow('uncertified'); await expect(b.checkpoint({kind:'model-start',turn:1,context})).rejects.toThrow('predecessor'); await expect(b.checkpoint({kind:'complete'})).rejects.toThrow('incomplete');f.journal.close();});
 test('ownership and cancellation fence stale dispatch',async()=>{const f=fixture(); f.journal.admit(spec());const claim=f.journal.claim('run','workspace');const b=f.journal.bridge(claim); const second=new DurableJournal({configRoot:f.root,key:f.key});expect(()=>second.claim('run','workspace')).toThrow('owned'); second.cancel('run','workspace'); await expect(b.checkpoint({kind:'model-start',turn:0,context})).rejects.toThrow('blocked');second.close();f.journal.close();});
 test('dead owner takeover increments epoch and old bridge is fenced',async()=>{const f=fixture();f.journal.admit(spec());const old=f.journal.claim('run','workspace');const b=f.journal.bridge(old); const second=new DurableJournal({configRoot:f.root,key:f.key,isProcessAlive:()=>false});expect(second.claim('run','workspace').epoch).toBe(old.epoch+1);await expect(b.checkpoint({kind:'model-start',turn:0,context})).rejects.toThrow('stale-owner');second.close();f.journal.close();});
 test('attempt and cost reservation limits persist on reopen',async()=>{const f=fixture(), s=spec();s.costPolicy={unit:'trusted-upper-bound',maxTotalUnits:5,maxUnitsPerAttempt:3};f.journal.admit(s);const c=f.journal.claim('run','workspace');await f.journal.bridge(c).checkpoint({kind:'model-start',turn:0,context});f.journal.release(c);f.journal.close();const j=new DurableJournal({configRoot:f.root,key:f.key});await expect(j.bridge(j.claim('run','workspace')).checkpoint({kind:'model-start',turn:0,context})).rejects.toThrow('budget');expect(j.get('run','workspace').reservedUnits).toBe(3);j.close();});
 test('identical completed admission remains idempotent after its deadline',async()=>{const f=fixture();const s=spec();f.journal.admit(s);const b=f.journal.bridge(f.journal.claim('run','workspace'));await b.checkpoint({kind:'model-start',turn:0,context});await b.checkpoint({kind:'model-result',turn:0,message:final});await b.checkpoint({kind:'complete'});const originalNow=Date.now;Date.now=()=>s.deadlineAt+1;try{expect(f.journal.admit(s).status).toBe('succeeded');expect(()=>f.journal.admit({...s,runId:'new',commandId:'new'})).toThrow('invalid-durable-admission');expect(()=>f.journal.admit({...s,context:{changed:true}})).toThrow('conflict');}finally{Date.now=originalNow;f.journal.close();}});
 test('identity conflicts and cross-workspace access fail closed',()=>{const f=fixture(),s=spec();f.journal.admit(s);expect(f.journal.admit(s).version).toBe(1);expect(()=>f.journal.admit({...s,context:{changed:true}})).toThrow('conflict');expect(()=>f.journal.get('run','other')).toThrow('not-found');f.journal.close();});
 test('wrong key rejected and backup cannot dispatch',()=>{const f=fixture();f.journal.admit(spec());expect(()=>new DurableJournal({configRoot:f.root,key:randomBytes(32)})).toThrow();const backup=join(f.root,'backup.sqlite');f.journal.backup(backup);const restored=join(f.root,'restored');mkdirSync(join(restored,'durable-execution'),{recursive:true});copyFileSync(backup,join(restored,'durable-execution/journal.sqlite'));expect(()=>new DurableJournal({configRoot:restored,key:f.key})).toThrow('backup-dispatch-disabled');f.journal.close();});
 test('oversized commit rolls back and never advances',async()=>{const f=fixture();f.journal.close();const j=new DurableJournal({configRoot:f.root,key:f.key,maxPayloadBytes:2000});j.admit(spec());const b=j.bridge(j.claim('run','workspace'));await b.checkpoint({kind:'model-start',turn:0,context});await expect(b.checkpoint({kind:'model-result',turn:0,message:{...final,content:[{type:'text',text:'x'.repeat(5000)}]}})).rejects.toThrow('payload-limit');expect(j.get('run','workspace').turns[0]!.message).toBeUndefined();j.close();});
 test('SQLite full error leaves checkpoint uncommitted and blocks later dispatch',async()=>{const f=fixture();f.journal.admit(spec());const b=f.journal.bridge(f.journal.claim('run','workspace'));await b.checkpoint({kind:'model-start',turn:0,context});const db=(f.journal as any).db;const pages=db.prepare('PRAGMA page_count').get().page_count;db.exec('PRAGMA max_page_count='+pages);await expect(b.checkpoint({kind:'model-result',turn:0,message:{...final,content:[{type:'text',text:randomBytes(100000).toString('hex')}]}})).rejects.toThrow();expect(f.journal.get('run','workspace').turns[0]!.message).toBeUndefined();await expect(b.checkpoint({kind:'model-start',turn:0,context})).rejects.toThrow('storage-unavailable');f.journal.close();});
 test('admission pins credential identity and exact runtime manifest',()=>{const f=fixture(),s=spec();expect(()=>f.journal.admit({...s,credentialIdentity:'unknown'})).toThrow('invalid-durable-admission');expect(()=>f.journal.admit({...s,runtimeManifest:{...s.runtimeManifest,piAi:'other'}})).toThrow('manifest-changed');f.journal.admit(s);expect(()=>f.journal.admit({...s,credentialIdentity:'b'.repeat(64)})).toThrow('conflict');const descriptor=f.journal.bridge(f.journal.claim('run','workspace')).descriptor;expect(Object.isFrozen(descriptor.runtimeManifest)).toBe(true);expect(descriptor.credentialIdentity).toBe(s.credentialIdentity);f.journal.close();});
 test('same journal cannot steal a live claim and projections omit private context',()=>{const f=fixture();f.journal.admit(spec());f.journal.claim('run','workspace');expect(()=>f.journal.claim('run','workspace')).toThrow('owned');expect(JSON.stringify(f.journal.list('workspace'))).not.toContain('SECRET');f.journal.close();});
 test('safeStorage envelope is stable; missing envelope with existing DB fails closed',()=>{const root=mkdtempSync(join(tmpdir(),'artist-key-'));roots.push(root);const protection={isEncryptionAvailable:()=>true,encryptString:(s:string)=>Buffer.from(s.split('').reverse().join('')),decryptString:(b:Buffer)=>b.toString().split('').reverse().join('')};const key=loadDurableKey(root,protection);expect(loadDurableKey(root,protection)).toEqual(key);const j=new DurableJournal({configRoot:root,key});j.close();unlinkSync(join(root,'durable-execution/key.envelope'));expect(()=>loadDurableKey(root,protection)).toThrow('key-missing');expect(()=>loadDurableKey(root,{...protection,getSelectedStorageBackend:()=> 'basic_text'})).toThrow('unavailable');});
});
process.on('exit',()=>{for(const root of roots)rmSync(root,{recursive:true,force:true});});
