import { afterEach, expect, test } from 'bun:test';
import { randomBytes } from 'node:crypto';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DurableJournal, type DurableRunSpec } from './index.ts';
import { DURABLE_RUNTIME_MANIFEST } from '../protocol/durable-execution.ts';
const cleanup:Array<()=>void>=[];afterEach(()=>cleanup.splice(0).reverse().forEach(fn=>fn()));
function fixture(){const root=mkdtempSync(join(tmpdir(),'durable-observation-')),key=randomBytes(32);cleanup.push(()=>rmSync(root,{recursive:true,force:true}));let journal=new DurableJournal({configRoot:root,key});cleanup.push(()=>journal.close());const spec:DurableRunSpec={runId:'r',workspaceId:'w',commandId:'admit',engine:'sqlite-v2-readonly-1',credentialIdentity:'a'.repeat(64),runtimeManifest:{...DURABLE_RUNTIME_MANIFEST},createdAt:Date.now(),deadlineAt:Date.now()+60000,allowedTools:['read'],model:'m',maxOutputTokens:10,maxModelAttempts:3,costPolicy:{unit:'verified-free',maxTotalUnits:0,maxUnitsPerAttempt:0},context:{},authority:{}};journal.admit(spec);const claim=journal.claim('r','w');journal.reserveOperation(claim,{slotId:'effect',adapterId:'test',adapterVersion:'1',credentialIdentity:spec.credentialIdentity,effectClass:'reconcilable-write',idempotencyKey:'key',input:{},outputSchema:{id:'test',version:'1'},maxAttempts:2,maxUnitsPerAttempt:0});const issued=journal.startOperation(claim,'effect','send').attempt!;return{get journal(){return journal},claim,issued,reopen(){journal.release(claim);journal.close();journal=new DurableJournal({configRoot:root,key})}}}
const validator={id:'test',version:'1',validate:(value:unknown)=>value==='confirmed'};
for(const action of ['pause','cancel'] as const)test(`reopen ${action} permits outcome reconciliation without revival or dispatch`,()=>{const f=fixture();f.journal.command({runId:'r',workspaceId:'w',commandId:action,expectedVersion:f.journal.get('r','w').version,action});f.reopen();const observer=f.journal.claimObservation('r','w');expect(observer.observationOnly).toBe(true);expect(f.journal.reconcileOperation(observer,f.issued,{kind:'succeeded',output:'confirmed'},validator).status).toBe('succeeded');expect(f.journal.get('r','w').status).toBe(action==='pause'?'paused':'cancelled');expect(()=>f.journal.startOperation(observer,'effect','again')).toThrow('observation-only');expect(()=>f.journal.bridge(observer)).toThrow('observation-only');f.journal.release(observer);});
test('later Resume and mutable claim fields cannot upgrade an observation lease',()=>{const f=fixture();f.journal.command({runId:'r',workspaceId:'w',commandId:'pause',expectedVersion:f.journal.get('r','w').version,action:'pause'});f.reopen();const observer=f.journal.claimObservation('r','w');f.journal.reconcileOperation(observer,f.issued,{kind:'not-applied',reason:'authoritative absence'});f.journal.command({runId:'r',workspaceId:'w',commandId:'resume',expectedVersion:f.journal.get('r','w').version,action:'resume'});delete observer.observationOnly;observer.controlRevision=f.journal.get('r','w').controlRevision;expect(()=>f.journal.startOperation(observer,'effect','retry')).toThrow('observation-only');expect(()=>f.journal.claim('r','w')).toThrow('run-owned');f.journal.release(observer);const execution=f.journal.claim('r','w');expect(f.journal.startOperation(execution,'effect','retry').dispatch).toBe(true);f.journal.release(execution);});
