import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

describe('Artist OS persistent shell chrome', () => {
  test('uses the thin ScriptOS-style sidebar and bottom-corner toggle', () => {
    const shell = readFileSync(join(import.meta.dir, '..', 'AppShell.tsx'), 'utf8')
    const styles = readFileSync(join(import.meta.dir, '..', '..', '..', 'index.css'), 'utf8')
    const openToggle = shell.indexOf('data-testid="sidebar-toggle-open"')
    const panelShell = shell.indexOf('=== OUTER LAYOUT: Unified Panel Stack')

    expect(openToggle).toBeGreaterThan(-1)
    expect(openToggle).toBeLessThan(panelShell)
    expect(shell).toContain('data-testid="sidebar-toggle-close"')
    expect(shell).toContain('pointer-events-auto absolute bottom-3 right-2 z-[80]')
    expect(shell).toContain('pointer-events-auto fixed bottom-3 left-2 z-[100]')
    expect(shell).toContain('usesWorkspaceHeader ? "px-3 pb-10 pt-10"')
    expect(shell).toContain('usesWorkspaceHeader && "artist-os-sidebar-glass"')
    expect(styles).toContain('.artist-os-sidebar-glass {')
    expect(styles).toContain('backdrop-filter: blur(28px) saturate(145%);')
    expect(shell).not.toContain('w-[56px]')
    expect(shell).not.toContain('<PanelLeftRounded')
  })

  test('keeps clickable traffic lights and the header divider permanently rendered', () => {
    const topBar = readFileSync(join(import.meta.dir, '..', 'TopBar.tsx'), 'utf8')
    const windowManager = readFileSync(
      join(import.meta.dir, '..', '..', '..', '..', 'main', 'window-manager.ts'),
      'utf8',
    )

    expect(topBar).toContain("RENDERER_PRODUCT_VARIANT === 'artist-os'")
    expect(topBar).toContain('data-testid="persistent-mac-window-controls"')
    expect(topBar).toContain('artist-os-topbar-glass border-b border-white/10 text-white')
    expect(topBar).toContain('bg-[#ff5f57]')
    expect(topBar).toContain('bg-[#febc2e]')
    expect(topBar).toContain('bg-[#28c840]')
    expect(topBar).toContain('window.electronAPI.closeWindow()')
    expect(topBar).toContain('window.electronAPI.menuMinimize()')
    expect(topBar).toContain('window.electronAPI.menuMaximize()')
    expect(windowManager).toContain("RUNTIME_IDENTITY.variant === 'artist-os' ? false : visible")
    expect(windowManager).toContain("window.on('restore', keepArtistTrafficLightsStable)")
    expect(windowManager).toContain('managed.window.setWindowButtonVisibility(shouldShow)')
  })

  test('groups HQ, Campaigns, and Lab beside the sidebar divider', () => {
    const shell = readFileSync(join(import.meta.dir, '..', 'AppShell.tsx'), 'utf8')
    const rail = readFileSync(join(import.meta.dir, '..', 'WorkspaceRail.tsx'), 'utf8')
    const topBar = readFileSync(join(import.meta.dir, '..', 'TopBar.tsx'), 'utf8')
    const styles = readFileSync(join(import.meta.dir, '..', '..', '..', 'index.css'), 'utf8')

    expect(shell).toContain('effectiveSidebarWidth + 14')
    expect(topBar).toContain('workspaceNavigationLeftInset - menuLeftPadding')
    expect(rail).toContain('data-testid="artist-place-switcher"')
    expect(rail).toContain('<span>HQ</span>')
    expect(rail).toContain('<span>Campaigns</span>')
    expect(rail).toContain('New Campaign')
    expect(rail).toContain("'Creating…' : 'Lab'")
    expect(styles).toContain('.artist-os-workspace-switcher {')
  })

  test('names the HQ and campaign agent front door Command', () => {
    const shell = readFileSync(join(import.meta.dir, '..', 'AppShell.tsx'), 'utf8')

    expect(shell).toMatch(/id: "nav:chat",\s+title: "Command",\s+label:[\s\S]*?icon: Sparkles/)
    expect(shell).toMatch(/id: "nav:work-chat",\s+title: "Command",\s+label:[\s\S]*?icon: Sparkles/)
    expect(shell).not.toContain('title: "Chat"')
    expect(shell).toContain('SONG_DIRECTOR_SLUG')
    expect(shell).toContain("{isLabWorkspace ? 'New Command' : 'New Chat'}")
  })

  test('keeps the black canvas scoped to Artist OS main content', () => {
    const panelSlot = readFileSync(join(import.meta.dir, '..', 'PanelSlot.tsx'), 'utf8')
    const styles = readFileSync(join(import.meta.dir, '..', '..', '..', 'index.css'), 'utf8')

    expect(panelSlot).toContain("const isChatRoute = navState?.navigator === 'sessions' && navState.details?.type === 'session'")
    expect(panelSlot).toContain("RENDERER_PRODUCT_VARIANT === 'artist-os' && !isChatRoute && 'artist-os-main-canvas'")
    expect(styles).toContain('.artist-os-main-canvas {')
    expect(styles).toContain('background: #050505;')
    expect(styles).toContain('.artist-os-main-canvas .bg-\\[\\#050505\\]')
  })

  test('lets Context and Outputs fill the main app canvas', () => {
    const panelSlot = readFileSync(join(import.meta.dir, '..', 'PanelSlot.tsx'), 'utf8')

    expect(panelSlot).toContain("navState?.navigator === 'outputs'")
    expect(panelSlot).toContain("navState?.navigator === 'workspaceContext'")
  })

  test('uses the global compact page header for HQ', () => {
    const hq = readFileSync(join(import.meta.dir, '..', 'ArtistHQHome.tsx'), 'utf8')
    const compactHeader = readFileSync(join(import.meta.dir, '..', 'CompactPageHeader.tsx'), 'utf8')

    expect(hq).toContain('<CompactPageHeader')
    expect(hq).toContain("const headerTone = tab === 'profile' || tab === 'branding' ? 'blue' : tab === 'voice' ? 'red' : 'orange'")
    expect(hq).toContain('dimBackgroundImage={SHOW_HQ_BANNER_FILTER}')
    expect(hq).toContain("borderless={tab === 'home'}")
    expect(hq).toContain("hero={tab === 'home'}")
    expect(hq).toContain("titleClassName={tab === 'home' ? 'text-[52px]' : undefined}")
    expect(hq).toContain("after:ring-2 after:ring-inset after:ring-[#050505]")
    expect(hq).not.toContain("!border-transparent")
    expect(compactHeader).toContain("!borderless && 'border'")
    expect(compactHeader).toContain("hero ? 'min-h-[240px]' : compact ? 'min-h-[80px]' : 'min-h-[108px]'")
    expect(compactHeader).toContain('const GLOBAL_HERO_BACKGROUND')
    expect(compactHeader).toContain('radial-gradient(70% 54% at 50% 118%')
    expect(compactHeader).toContain('linear-gradient(90deg, #D90B16 0%, #F22409 20%, #FF5A00 50%')
    expect(compactHeader).not.toContain('globalHeroBackground')
    expect(compactHeader).toContain('backgroundImage: `url(${JSON.stringify(backgroundImage)})`')
    expect(compactHeader).toContain('rounded-[22px]')
    expect(compactHeader).not.toContain('rounded-full blur')
    expect(compactHeader).toContain('className="min-w-0 self-end"')
    expect(compactHeader).toContain("hero ? 'text-[52px]' : 'text-[26px]'")
  })

  test('uses one direct People destination and a shared compact Network/Community header', () => {
    const hq = readFileSync(join(import.meta.dir, '..', 'ArtistHQHome.tsx'), 'utf8')
    const community = readFileSync(join(import.meta.dir, '..', 'CommunityPage.tsx'), 'utf8')
    const peopleHeader = readFileSync(join(import.meta.dir, '..', 'PeoplePageHeader.tsx'), 'utf8')
    const shell = readFileSync(join(import.meta.dir, '..', 'AppShell.tsx'), 'utf8')
    const peopleStart = shell.indexOf('id: "nav:people"')
    const peopleItem = shell.slice(peopleStart, shell.indexOf('id: "nav:work"', peopleStart))

    expect(peopleItem).toContain("onClick: () => handleArtistHQNavClick('network')")
    expect(peopleItem).not.toContain('expandable: true')
    expect(peopleItem).not.toContain('items: [')
    expect(hq).toMatch(/<PeoplePageHeader\s+activeView="network"/)
    expect(community).toContain('<PeoplePageHeader activeView="community"')
    expect(peopleHeader).toContain('<CompactPageHeader')
    expect(peopleHeader).toContain('tone="emerald"')
    expect(peopleHeader).toContain('role="tablist"')
    expect(peopleHeader).toContain("(['network', 'community'] as const)")
    expect(hq).toContain('aria-label="Search people"')
    expect(hq).toContain('justify-end gap-2')
    expect(hq).toContain('aria-label="Add person"')
    expect(hq).toContain('<TooltipContent>Add person</TooltipContent>')
    expect(hq).toContain('aria-expanded={categoryFormOpen}')
    expect(hq).toContain('placeholder="New category"')
    expect(hq).toContain('aria-label={`Rename ${category.label}`}')
    expect(hq).toContain('aria-label={`Delete ${category.label}`}')
    expect(hq).toContain('aria-label="People categories"')
    expect(hq.indexOf('<NetworkCategoryGrid')).toBeLessThan(hq.indexOf('aria-label="Search people"'))
    expect(hq).toContain('aria-pressed={selected}')
    expect(hq).toContain('aria-label={`Add person to ${category.label}`}')
    expect(hq).toContain('value === categoryId ? null : categoryId')
    expect(hq).toContain('<DialogTitle className="text-lg font-medium tracking-[-0.02em]">Add person</DialogTitle>')
    expect(hq).toContain('placeholder="Email"')
    expect(hq).not.toContain('placeholder="Contact"')
    expect(hq).toContain('Use a category + to add someone.')
    expect(hq).toContain('className="group flex h-12 w-fit min-w-[150px] max-w-[220px]')
    expect(hq).toContain('className="flex flex-wrap gap-2"')
    expect(hq).toContain("person.starred ? 'text-[#f97316]'")
    expect(hq).toContain("{person.starred ? 'Unstar person' : 'Star person'}")
    expect(hq).toContain('Number(Boolean(right.starred)) - Number(Boolean(left.starred))')
    expect(hq).not.toContain('No role added')
    expect(hq).not.toContain('placeholder="New category name"')
    expect(community).toContain('aria-label="Community actions"')
    expect(community).toContain('<StyledDropdownMenuContent align="end"')
    expect(community).toContain('Connect Gmail')
    expect(community).toContain('aria-expanded={addFanOpen}')
    expect(community).toContain('mt-3 rounded-2xl border border-white/[0.025] bg-[#0C0D0E] p-4')
    expect(community).toContain('bg-[#0C0D0E] p-4')
    expect(community).toContain('aria-expanded={emailQueueOpen}')
    expect(community).not.toContain('<MetricCard')
    expect(community).not.toContain('xl:grid-cols-[minmax(0,1fr)_340px]')
    expect(community).not.toContain('>Next Moves</h2>')
  })

  test('keeps outside intelligence in a direct Signals destination instead of Brain', () => {
    const hq = readFileSync(join(import.meta.dir, '..', 'ArtistHQHome.tsx'), 'utf8')
    const shell = readFileSync(join(import.meta.dir, '..', 'AppShell.tsx'), 'utf8')
    const peopleStart = shell.indexOf('id: "nav:people"')
    const signalsStart = shell.indexOf('id: "nav:signals"', peopleStart)
    const workStart = shell.indexOf('id: "nav:work"', signalsStart)
    const brainStart = shell.indexOf('id: "nav:brain"', workStart)
    const brainItems = shell.slice(brainStart, shell.indexOf('return result', brainStart))

    expect(signalsStart).toBeGreaterThan(peopleStart)
    expect(workStart).toBeGreaterThan(signalsStart)
    expect(shell.slice(signalsStart, workStart)).toContain("onClick: () => handleArtistHQNavClick('signals')")
    expect(brainItems).not.toContain('nav:research')
    expect(brainItems).not.toContain('Intel Docs')
    expect(hq).toContain("case 'signals':")
    expect(hq).toContain('title: \'Signals\'')
    expect(hq).toContain("if (raw === 'research') return 'signals'")
    expect(hq).toContain('aria-label="Signals intelligence reader"')
    expect(hq).toContain('Save selection')
    expect(hq).toContain('SIGNAL_NUGGETS_CONTEXT_SLUG')
    expect(hq).toContain('WEEKLY_SIGNAL_SCAN_SLUG')
    expect(hq).toContain('createSignalScanQueueWorkAction')
    expect(hq).toContain("automationName: 'Manual Signal Scan'")
    expect(hq).toContain("const INTEL_SYNC_AUTOMATION_NAME = 'Weekly Signal Scan'")
  })

  test('keeps the HQ Plan page available while hiding its navigation entry behind a flag', () => {
    const hq = readFileSync(join(import.meta.dir, '..', 'ArtistHQHome.tsx'), 'utf8')
    const shell = readFileSync(join(import.meta.dir, '..', 'AppShell.tsx'), 'utf8')
    const planItem = shell.slice(shell.indexOf('id: "nav:plan"'), shell.indexOf('id: "nav:people"'))
    const calendar = hq.indexOf('<ArtistCalendarView')
    const board = hq.indexOf('<AgendaPage', calendar)
    const planCardEnd = hq.indexOf('</HQCard>', board)

    expect(hq).toContain("{tab !== 'calendar' && tab !== 'network' ? (")
    expect(hq).toContain('title="Plan"')
    expect(hq).toContain('title="Plan"\n            tone="orange"')
    expect(hq).toContain('<ArtistCalendarView\n                  compact')
    expect(board).toBeGreaterThan(calendar)
    expect(planCardEnd).toBeGreaterThan(board)
    expect(hq).toContain('embedded\n                    sessions={agendaSessions}')
    expect(hq).toContain('lg:grid-cols-[minmax(0,2.15fr)_minmax(300px,0.85fr)]')
    expect(hq).toContain('id="plan-kanban" className="min-h-[280px] overflow-hidden border-t')
    expect(hq).toContain('lg:border-l lg:border-t-0')
    expect(hq).not.toContain('planBoardOpen')
    expect(hq).toContain("tab === 'calendar' ? 'overflow-hidden' : 'overflow-y-auto'")
    expect(shell).toContain('const SHOW_HQ_PLAN_NAV = false')
    expect(shell).toMatch(/if \(SHOW_HQ_PLAN_NAV\) \{\s+result\.push\(\{ id: 'nav:plan'/)
    expect(shell).toMatch(/\.\.\.\(\(SHOW_HQ_PLAN_NAV \? \[\{\s+id: "nav:plan"/)
    expect(shell).toMatch(/id: "nav:calendar",\s+title: "Plan"/)
    const agenda = readFileSync(join(import.meta.dir, '..', 'AgendaPage.tsx'), 'utf8')
    expect(agenda).toContain('aria-label="Add task to To Do"')
    expect(agenda).toContain("embedded && 'min-h-0 flex-1 overflow-y-auto overscroll-contain pr-0.5'")
    expect(agenda).toContain("? 'h-full min-h-0 grid-rows-3 divide-y divide-white/[0.055]'")
    expect(agenda).toContain("? 'flex min-h-0 flex-col px-3 py-2.5'")
    expect(agenda).not.toContain('Nothing here.')
    expect(agenda).toContain('Delete task')
    expect(agenda).toContain('Discussion')
    expect(agenda).not.toContain('Open Thread')
    expect(planItem).toContain("onClick: () => handleArtistHQNavClick('calendar')")
    expect(planItem).not.toContain('expandable: true')
  })

  test('uses one compact Work header with in-page Workers, Workflows, and Automations tabs', () => {
    const shell = readFileSync(join(import.meta.dir, '..', 'AppShell.tsx'), 'utf8')
    const workers = readFileSync(join(import.meta.dir, '..', 'AgentsLaunchpad.tsx'), 'utf8')
    const workflows = readFileSync(join(import.meta.dir, '..', '..', '..', 'pages', 'WorkflowsListPage.tsx'), 'utf8')
    const automations = readFileSync(join(import.meta.dir, '..', 'MainContentPanel.tsx'), 'utf8')
    const tabs = readFileSync(join(import.meta.dir, '..', 'WorkPageTabs.tsx'), 'utf8')
    const compactHeader = readFileSync(join(import.meta.dir, '..', 'CompactPageHeader.tsx'), 'utf8')

    expect(workers).toContain('tone="orange"')
    expect(workers).toContain('className="mb-4"')
    expect(workers).not.toContain('!min-h-[112px]')
    expect(workers).toContain("title={labOnly ? 'Workers' : 'Work'}")
    expect(workflows).toContain('title="Work"')
    expect(workflows).toContain('tone="orange"')
    expect(workflows).toContain('Workflow library')
    expect(workflows).not.toContain('bg-violet')
    expect(workflows).toContain('folder.workflows.map((workflow)')
    expect(workflows).not.toContain('function WorkflowFolderCard')
    expect(automations).toContain("title={workTab ? 'Work' : title}")
    expect(automations).toContain("tone={workTab ? 'orange' : 'blue'}")
    expect(tabs).toContain("{ id: 'workers', label: 'Workers'")
    expect(tabs).toContain("{ id: 'workflows', label: 'Workflows'")
    expect(tabs).toContain("{ id: 'active', label: 'Active'")
    expect(tabs).toContain('routes.view.automations()')
    expect(shell).toContain("result.push({ id: 'nav:work', type: 'nav', action: handleAgentsClick })")
    expect(compactHeader.split('border-orange-100/[0.12]').length - 1).toBe(5)
  })

  test('makes the Workers directory chat-first without hiding worker descriptions', () => {
    const workers = readFileSync(join(import.meta.dir, '..', 'AgentsLaunchpad.tsx'), 'utf8')
    const useAgents = readFileSync(join(import.meta.dir, '..', '..', '..', 'hooks', 'useAgents.ts'), 'utf8')

    expect(workers).toContain('placeholder="Search workers by name or capability"')
    expect(workers).toContain("type WorkerDirectoryView = 'all' | 'recent' | 'favorites'")
    expect(workers).toContain('onClick={onStartChat}')
    expect(workers).toContain('aria-label={`Start chat with ${name}`}')
    expect(workers).toContain('aria-label={`Configure ${name}`}')
    expect(workers).toContain('{description}')
    expect(workers).toContain('space-y-6')
    expect(workers).toContain('group/category')
    expect(workers).toContain('group/category mb-4')
    expect(workers).toContain('h-[22px]')
    expect(workers).toContain('defaultVisibleSlugs={defaultVisibleSlugs}')
    expect(workers).toContain('includeSystemVisibleAgents: !labOnly')
    expect(workers).toContain('allowedAgentSet.has(a.slug)')
    expect(workers).toContain('allowedAgentSlugs={allowedAgentSlugs}')
    expect(workers).toContain("slug === 'the-excavator' || slug === 'reverse-magic') return 'Inspiration'")
    expect(workers).toContain("slug === 'legendary-writer' || slug === 'hooker' || slug === 'reference-master') return 'Writing'")
    expect(workers).toContain("if (slug === 'record-doctor') return 'Song Development'")
    expect(workers).toContain("if (slug === 'catalog-royalty-agent' || slug === 'legal-agent')")
    expect(workers).toContain("return 'Business Operations'")
    expect(workers).not.toContain("return 'Rights & Royalties'")
    expect(workers).not.toContain("return 'Legal & Deals'")
    expect(workers).toContain("if (slug === 'x-editorial')")
    expect(workers).toContain("return 'Socials'")
    expect(workers).toContain('text-white/72')
    expect(workers).not.toContain('<MessageSquare')
    expect(useAgents).toContain("'lottie-animation-agent'")
    expect(workers).not.toContain('onClick={() => setSelectedAgent(agent)}')
  })

  test('keeps Artist OS chat and notification text visible on black surfaces', () => {
    const chat = readFileSync(join(import.meta.dir, '..', 'ChatDisplay.tsx'), 'utf8')
    const input = readFileSync(join(import.meta.dir, '..', 'input', 'FreeFormInput.tsx'), 'utf8')
    const agentHeader = readFileSync(join(import.meta.dir, '..', 'ChatAgentHeader.tsx'), 'utf8')
    const bell = readFileSync(join(import.meta.dir, '..', '..', 'notifications', 'BellMenu.tsx'), 'utf8')
    const notification = readFileSync(join(import.meta.dir, '..', '..', 'notifications', 'NotificationItem.tsx'), 'utf8')

    expect(input).toContain("RENDERER_PRODUCT_VARIANT === 'artist-os' ? 'rgba(255, 255, 255, 0.92)' : undefined")
    expect(input).toContain("'bg-[#f4511e] text-white hover:bg-[#ff5a22] active:bg-[#dc3f18]")
    expect(input).toContain("'bg-white text-black hover:bg-white/90 active:bg-white/80'")
    expect(input).toContain("variant={RENDERER_PRODUCT_VARIANT === 'artist-os' ? 'default' : 'secondary'}")
    expect(input).toContain("window.addEventListener('craft:insert-text'")
    expect(chat).toContain('runner-chat-response relative max-w-[90%] pl-6 pr-4 py-3 text-[13.5px] leading-[25px]')
    expect(agentHeader).toContain('items-center justify-center')
    expect(agentHeader).toContain('rounded-[10px] border border-[#ff8063]/[0.34]')
    expect(agentHeader).not.toContain('bg-[#f4512c]')
    expect(agentHeader).toContain('shadow-tinted')
    expect(agentHeader).toContain('font-medium uppercase tracking-[0.13em]')
    expect(agentHeader).toContain('<TooltipContent side="bottom"')
    expect(agentHeader).not.toContain('<p')
    expect(bell).toContain('className="w-[360px] p-0 !text-white"')
    expect(notification).toContain("'border-l-2 px-3 py-2 text-sm text-white'")
  })

  test('keeps weekly manager routing labels out of the Artist OS chat controls', () => {
    const badges = readFileSync(join(import.meta.dir, '..', 'ActiveOptionBadges.tsx'), 'utf8')

    expect(badges).toContain('ARTIST_OS_HIDDEN_CHAT_LABEL_IDS')
    expect(badges).toContain("'manager', 'artist-hq', 'weekly'")
    expect(badges).toContain("RENDERER_PRODUCT_VARIANT === 'artist-os'")
  })

  test('uses two honest artist-facing action modes while preserving real permission wiring', () => {
    const shell = readFileSync(join(import.meta.dir, '..', 'AppShell.tsx'), 'utf8')
    const badges = readFileSync(join(import.meta.dir, '..', 'ActiveOptionBadges.tsx'), 'utf8')
    const compact = readFileSync(join(import.meta.dir, '..', 'input', 'CompactPermissionModeSelector.tsx'), 'utf8')
    const chatPage = readFileSync(join(import.meta.dir, '..', '..', '..', 'pages', 'ChatPage.tsx'), 'utf8')

    expect(shell).toContain("RENDERER_PRODUCT_VARIANT === 'artist-os' ? ARTIST_OS_PERMISSION_MODES")
    expect(badges).toContain('ARTIST_OS_PERMISSION_MODES.map')
    expect(badges).toContain("onClick={() => handleSelect(mode)}")
    expect(compact).toContain("? ARTIST_OS_PERMISSION_MODES")
    expect(chatPage).toContain('normalizeArtistPermissionMode(sessionOpts.permissionMode)')
    expect(chatPage).toContain("setPermissionMode('ask')")
    expect(chatPage).toContain('permissionMode={permissionMode}')
  })

  test('routes all major HQ and workspace page headers through the compact system', () => {
    const files = [
      'ArtistCommandCenterHome.tsx',
      'CampaignCalendarPage.tsx',
      'AgendaPage.tsx',
      'VaultPage.tsx',
      'LabWorkspaceHome.tsx',
      'LabSongsPage.tsx',
      'LabSequencePage.tsx',
    ]

    for (const file of files) {
      const source = readFileSync(join(import.meta.dir, '..', file), 'utf8')
      expect(source).toContain('<CompactPageHeader')
      expect(source).not.toContain('text-[56px]')
      expect(source).not.toContain('min-h-[230px]')
    }
  })

  test('shows the release countdown beside a compact readiness handoff on campaign overview', () => {
    const campaign = readFileSync(join(import.meta.dir, '..', 'ArtistCommandCenterHome.tsx'), 'utf8')
    const dial = readFileSync(join(import.meta.dir, '..', 'ReleaseCountdownDial.tsx'), 'utf8')

    expect(campaign).toContain('missionCampaignWindow(mission)')
    expect(campaign).toContain('releaseDate={campaignWindow.releaseDate}')
    expect(campaign).toContain('<ReleaseReadinessSummary')
    expect(campaign).toContain("navigate(routes.view.campaign('release-board'))")
    expect(campaign).toContain('md:grid-cols-[minmax(0,1fr)_148px]')
    expect(dial).toContain('h-[136px] w-[136px]')
    expect(dial).not.toContain('#2b2b2f')
    expect(dial).not.toContain('#242428')
  })

  test('closes the Release Kit audio versions menu when clicking outside it', () => {
    const releaseKit = readFileSync(join(import.meta.dir, '..', 'ReleaseKitPage.tsx'), 'utf8')

    expect(releaseKit).toContain("document.addEventListener('pointerdown', closeVersions)")
    expect(releaseKit).toContain('versions.contains(event.target)')
    expect(releaseKit).toContain('versions.open = false')
    expect(releaseKit).toContain('ref={versionsRef}')
  })

  test('gives Release Board assets and agent actions a dedicated campaign page', () => {
    const campaign = readFileSync(join(import.meta.dir, '..', 'ArtistCommandCenterHome.tsx'), 'utf8')
    const main = readFileSync(join(import.meta.dir, '..', 'MainContentPanel.tsx'), 'utf8')
    const shell = readFileSync(join(import.meta.dir, '..', 'AppShell.tsx'), 'utf8')

    expect(campaign).toContain('function ReleaseBoardWorkspace')
    expect(campaign).toContain('function ReleaseBoardBand')
    expect(campaign).toContain('function ReleaseBoardSection')
    expect(campaign).toContain('activeItems.map((item)')
    expect(campaign).toContain('Choose an action for ${item.label}')
    expect(campaign).toContain('const optionalItems = category.items.filter((item) => item.tier !== \'core\')')
    expect(campaign).toContain('More options')
    expect(campaign).toContain('md:divide-x md:divide-y-0')
    expect(campaign).toContain("category.id === 'promotion' && 'md:grid-cols-2 lg:grid-cols-3'")
    expect(campaign).toContain('flex min-h-7 items-center')
    expect(campaign).toContain('<ReleaseBoardProgress board={releaseBoard} />')
    expect(campaign).toContain('max-w-[360px]')
    expect(campaign).toContain('{remaining} left')
    expect(campaign).toContain("backgroundColor: '#090909'")
    expect(campaign).toContain('rgba(255,77,0,0.018)')
    expect(campaign).toContain("'truncate text-[11px] font-normal'")
    expect(campaign).toContain('Open essentials')
    expect(main).toContain("navState.subpage === 'release-board'")
    expect(main).toContain('view="release-board"')
    expect(shell).toMatch(/id: "nav:release-board",\s+title: "Essentials"/)
    expect(campaign).not.toContain('function ReleaseBoardDialog')
    expect(campaign).not.toContain('selectedReleaseCategoryId')
  })

  test('visually rhymes Release Kit cards with Essentials without changing their layouts', () => {
    const releaseKit = readFileSync(join(import.meta.dir, '..', 'ReleaseKitPage.tsx'), 'utf8')

    expect(releaseKit).toContain("const RELEASE_KIT_SURFACE_CLASS = 'group/release-kit relative overflow-hidden rounded-2xl ring-1 ring-white/[0.055]'")
    expect(releaseKit).toContain("backgroundColor: '#090909'")
    expect(releaseKit).toContain('rgba(255,77,0,0.018)')
    expect(releaseKit).toContain('group-hover/release-kit:opacity-100')
    expect(releaseKit).toContain('text-[11px] font-medium text-white/90')
    expect(releaseKit).toContain("lg:grid-cols-[240px_minmax(0,1fr)]")
    expect(releaseKit).toContain('aspect-[9/16]')
  })

  test('keeps social video Variant Sets discoverable and resumable', () => {
    const releaseKit = readFileSync(join(import.meta.dir, '..', 'ReleaseKitPage.tsx'), 'utf8')
    const outputs = readFileSync(join(import.meta.dir, '..', '..', 'outputs', 'OutputsListPanel.tsx'), 'utf8')
    const outputDetail = readFileSync(join(import.meta.dir, '..', '..', '..', 'pages', 'OutputDetailPage.tsx'), 'utf8')
    const vault = readFileSync(join(import.meta.dir, '..', 'VaultPage.tsx'), 'utf8')
    const recovery = readFileSync(join(import.meta.dir, '..', '..', '..', 'lib', 'release-kit-repurpose.ts'), 'utf8')

    expect(releaseKit).toContain("'finals' | 'variants' | 'outputs'")
    expect(releaseKit).toContain('>Variants</TabButton>')
    expect(releaseKit).toContain('getSessionMessages(set.editorSessionId)')
    expect(releaseKit).toContain('rebindSocialVariantSet')
    expect(releaseKit).toContain('onCreate={() =>')
    expect(releaseKit).toContain('<Scissors className="mr-1.5 h-3.5 w-3.5" />Create variants')
    expect(recovery).toContain('preserve every ready version')
    expect(recovery).toContain('finish only missing or failed versions')
    expect(releaseKit).toContain('existing.messages.length === 0')
    expect(releaseKit).toContain('Instagram Trial scheduling is not available yet')
    expect(releaseKit).toContain('will not silently turn a Trial variant into a normal Reel')
    expect(outputs).toContain("'all' | 'variants'")
    expect(outputs).toContain("output.socialVariantSetSummary")
    expect(outputs).toContain("origin: 'output' as const")
    expect(outputs).toContain('displayOutputAssetPath(output.id, output.primary.path)')
    expect(outputs).toContain('<SocialVariantSetupDrawer')
    expect(outputDetail).toContain('Choose the campaign')
    expect(outputDetail).toContain('sourceWorkspaceId: manifest.workspaceId')
    expect(vault).toContain('<SocialVariantSetupDrawer')
  })

  test('creates an empty Lab song from the Songs page before opening the Pad', () => {
    const songs = readFileSync(join(import.meta.dir, '..', 'LabSongsPage.tsx'), 'utf8')
    const pad = readFileSync(join(import.meta.dir, '..', 'LabSongPadPage.tsx'), 'utf8')
    const collectionPicker = readFileSync(join(import.meta.dir, '..', 'LabCollectionPicker.tsx'), 'utf8')

    expect(songs).toContain('createLabUiSong')
    expect(songs).toContain('placeholder="Song title"')
    expect(songs).toContain('LabCollectionPicker')
    expect(songs).toContain('Collection: {collection}')
    expect(songs).toContain('Add to Songs')
    expect(songs).toContain("project: draftCollection.trim() || 'Loose Singles'")
    expect(songs).toContain('onClick={() => setAddSongOpen(true)}')
    expect(songs).toContain('deleteLabUiSong')
    expect(songs).toContain('Save changes')
    expect(songs).toContain('open={Boolean(editingSongId)}')
    expect(songs).toContain('Update how this song appears across the Lab.')
    expect(pad).toContain('<LabCollectionPicker')
    expect(collectionPicker).toContain('New collection...')
    expect(collectionPicker).toContain("const DEFAULT_COLLECTION = 'Loose Singles'")
  })

  test('keeps Spark capture available across the Lab with a searchable bank', () => {
    const shell = readFileSync(join(import.meta.dir, '..', 'AppShell.tsx'), 'utf8')
    const dock = readFileSync(join(import.meta.dir, '..', 'LabSparkDock.tsx'), 'utf8')

    expect(shell).toContain('<LabSparkDock workspaceId={activeWorkspaceId} attachToCurrentSong={labPadActive} />')
    expect(dock).toContain('Catch the spark')
    expect(dock).toContain('Open Spark Bank')
    expect(dock).toContain('filterLabSparks')
    expect(dock).toContain('Attached to ${activeSongTitle}')
    expect(dock).toContain('Edit spark')
    expect(dock).toContain('aria-label="Spark type"')
    expect(dock).toContain('aria-label="Spark tags"')
    expect(dock).toContain('Delete this Spark? This cannot be undone.')
  })

  test('connects Lab Home to the canonical Spark Bank and bounded songwriting team', () => {
    const shell = readFileSync(join(import.meta.dir, '..', 'AppShell.tsx'), 'utf8')
    const home = readFileSync(join(import.meta.dir, '..', 'LabWorkspaceHome.tsx'), 'utf8')
    const main = readFileSync(join(import.meta.dir, '..', 'MainContentPanel.tsx'), 'utf8')

    expect(shell).not.toContain('title: "Drafts"')
    expect(home).toContain('loadLabUiSparks')
    expect(home).toContain('openLabSparkBank')
    expect(home).toContain('LAB_DEFAULT_WORKER_SLUGS')
    expect(home).toContain('title="Continue writing"')
    expect(home).toContain('title="Spark bank"')
    expect(home).toContain('compact')
    expect(home).not.toContain('title="Lab Team"')
    expect(main).toContain('labOnly={isLabWorkspace(activeWorkspace, workspaces)}')
    expect(home).toContain("routes.view.agents('reference-master')")
    expect(home).not.toContain('song.rememberText')
  })

  test('self-heals declared songwriting skills before a Pad worker launches', () => {
    const pad = readFileSync(join(import.meta.dir, '..', 'LabSongPadPage.tsx'), 'utf8')

    expect(pad).toContain('ensureAgentDeclaredSkillsEnabled')
    expect(pad).toMatch(/ensureAgentDeclaredSkillsEnabled\([\s\S]*?buildAgentCreateSessionOptions/)
  })

  test('explains Song Pad tools and avoids stacking its two writing panes', () => {
    const pad = readFileSync(join(import.meta.dir, '..', 'LabSongPadPage.tsx'), 'utf8')

    expect(pad).toContain('How Song Pad works')
    expect(pad).toContain('Find rhymes')
    expect(pad).toContain('Keep alternate lines')
    expect(pad).toContain('Move ideas into place')
    expect(pad).toContain('Ask a writing specialist')
    expect(pad).toContain('Catch sparks anywhere')
    expect(pad).toContain("const [compactPane, setCompactPane] = React.useState<SongPadPane>('rough')")
    expect(pad).toContain("compactPane === 'rough' ? 'flex' : 'hidden xl:flex'")
    expect(pad).toContain("compactPane === 'final' ? 'flex' : 'hidden xl:flex'")
  })

  test('lets writers delete extra sequence pages without deleting their songs', () => {
    const sequence = readFileSync(join(import.meta.dir, '..', 'LabSequencePage.tsx'), 'utf8')

    expect(sequence).toContain('removeLabSequencePage')
    expect(sequence).toContain('Songs stay in your library.')
    expect(sequence).toContain('Delete sequence page')
    expect(sequence).toContain('aria-expanded={addOpen}')
    expect(sequence).toContain("addOpen && 'rotate-45'")
    expect(sequence).not.toContain('<Music2')
  })

  test('lets writers persist Focus and Status directly from the Songs list', () => {
    const songs = readFileSync(join(import.meta.dir, '..', 'LabSongsPage.tsx'), 'utf8')

    expect(songs).toContain('upsertLabUiSong')
    expect(songs).toContain('onSetFocused')
    expect(songs).toContain('onSetStatus')
    expect(songs).toContain('aria-pressed={song.focused}')
    expect(songs).toContain('Status for ${song.title}')
  })

  test('keeps HQ cards darker than soot but distinct from the black canvas', () => {
    const hq = readFileSync(join(import.meta.dir, '..', 'ArtistHQHome.tsx'), 'utf8')

    expect(hq).toContain("bg-[#0C0D0E] p-4")
    expect(hq).toContain('divide-x divide-white/[0.075] overflow-hidden rounded-[14px]')
  })

  test('places the lifecycle activity card below the Release Horizon', () => {
    const hq = readFileSync(join(import.meta.dir, '..', 'ArtistHQHome.tsx'), 'utf8')
    const releaseHorizon = hq.indexOf('<ReleaseHorizon')
    const nextMove = hq.indexOf('<StateOfPlayPanel')
    const activity = hq.indexOf('workerItems={workerItems}', nextMove)

    expect(releaseHorizon).toBeGreaterThan(-1)
    expect(nextMove).toBeGreaterThan(releaseHorizon)
    expect(activity).toBeGreaterThan(nextMove)
    expect(hq).not.toContain('<LiveWorkChip')
    expect(hq).not.toContain('<RecentActivity')
    expect(hq).toContain('aria-label="Work activity"')
    expect(hq).toContain("['needs', 'Needs you']")
    expect(hq).toContain("['progress', 'In progress']")
    expect(hq).toContain("['recent', 'Recent']")
    expect(hq).toContain('.filter((move) => move.attentionRequired)')
    expect(hq).toContain('completedOutputs.map((output)')
    expect(hq).not.toContain('>Active work</span>')
    expect(hq).toContain('h-1 w-1 shrink-0 rounded-full bg-white/28')
    expect(hq).toContain('min-w-0 flex-1 truncate text-xs font-semibold text-white/88')
    expect(hq).not.toContain('>Priority</p>')
    expect(hq).not.toContain('after:bg-[#f97316]')
    expect(hq).toContain('inset_0_0_0_1px_rgba(249,115,22,0.62)')
  })

  test('places the Pulse stack directly below the HQ header', () => {
    const hq = readFileSync(join(import.meta.dir, '..', 'ArtistHQHome.tsx'), 'utf8')

    expect(hq).not.toContain('<span>More details</span>')
    expect(hq).not.toContain('PIN_HQ_PULSES_TO_BOTTOM')
    expect(hq).not.toContain('className="flex min-h-[calc(100dvh-176px)] flex-col"')
    expect(hq).toContain('id="hq-home-operations" className="space-y-3"')
    expect(hq).toContain('<div id="hq-home-details">')
    expect(hq).toContain('<SignalsStrip')
    expect(hq).toContain('group relative flex h-[104px] w-full min-w-0 flex-col overflow-hidden p-3.5')
    expect(hq).toContain('divide-x divide-white/[0.075] overflow-hidden rounded-[14px]')
    expect(hq).toContain('backdrop-blur-2xl')
    expect(hq).not.toContain('border border-[#f97316]/35')
    expect(hq).toContain('ariaLabel="Open Spotify Pulse analysis"')
    expect(hq).toContain('ariaLabel="Open Social Pulse analysis"')
    expect(hq).toContain('<PulseDetailsDialog')
    expect(hq).not.toContain('mt-3 grid grid-cols-3 gap-2 rounded-[12px] bg-black/20 py-3')
    expect(hq).toContain('placeholder="Tell your manager what you need…"')
    expect(hq).not.toContain('h-1.5 w-1.5 shrink-0 rounded-full bg-[#f97316]')
    expect(hq).not.toContain('>This week</span>')
    expect(hq).toContain('aria-label="Work activity"')
    expect(hq).toContain('userFacingHqAttention(state.attention)')
  })

  test('does not leave a former North Star spacer before HQ analytics', () => {
    const hq = readFileSync(join(import.meta.dir, '..', 'ArtistHQHome.tsx'), 'utf8')
    // The profile schema lives in packages/shared now; the renderer lib module
    // is a re-export and no longer carries the field declarations.
    const profile = readFileSync(
      join(import.meta.dir, '..', '..', '..', '..', '..', '..', '..', 'packages', 'shared', 'src', 'artist-context', 'profile.ts'),
      'utf8',
    )
    const operations = hq.indexOf('id="hq-home-operations"')
    const spotify = hq.indexOf('<SignalsStrip', operations)

    expect(operations).toBeGreaterThan(-1)
    expect(spotify).toBeGreaterThan(operations)
    expect(hq).not.toContain('min-h-[clamp(280px,42vh,420px)] flex-1 bg-[#050505]')
    expect(hq).not.toContain('<ArtistNorthStar')
    expect(hq).not.toContain('North Star</p>')
    expect(hq).not.toContain('What are you building toward?')
    expect(hq).toContain('Artist mission / North Star')
    expect(profile).toContain('mission?: string')
  })

  test('orders Spotify before Social and keeps Social focused on Instagram analytics', () => {
    const hq = readFileSync(join(import.meta.dir, '..', 'ArtistHQHome.tsx'), 'utf8')
    const strip = hq.slice(hq.indexOf('function SignalsStrip'), hq.indexOf('function SignalTile'))
    const spotify = strip.indexOf("label={spotifyPublicApi ? 'Popularity' : 'Streams'}")
    const social = strip.indexOf('value={formatMetric(instagramSnapshot?.metrics.followers)}')
    const intel = hq.indexOf('<IntelPulseCard')

    expect(spotify).toBeGreaterThan(-1)
    expect(social).toBeGreaterThan(spotify)
    expect(intel).toBe(-1)
    expect(hq).toContain('<SignalStat label="Followers"')
    expect(hq).toContain('<SignalStat label="Reach"')
    expect(hq).toContain('<SignalStat label="Interactions"')
    expect(hq).not.toContain('<SignalStat label="Profiles"')
    expect(hq).not.toContain('<SignalStat label="Account sets"')
  })
})
