import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

describe('Social Pulse Instagram layout', () => {
  test('keeps controls and shows real views when growth is unavailable', () => {
    const source = readFileSync(join(import.meta.dir, '..', 'ArtistHQHome.tsx'), 'utf8')
    const stripStart = source.indexOf('function SignalsStrip')
    const stripEnd = source.indexOf('function SignalTile')
    const strip = source.slice(stripStart, stripEnd)
    const detailsStart = source.indexOf('function SocialPulseDetails')
    const detailsEnd = source.indexOf('function formatSignedMetric')
    const details = source.slice(detailsStart, detailsEnd)
    const spotifyDetailsStart = source.indexOf('function SpotifyPulseDetails')
    const spotifyDetailsEnd = source.indexOf('function SignalStat')
    const spotifyDetails = source.slice(spotifyDetailsStart, spotifyDetailsEnd)

    expect(source).toContain("const INSTAGRAM_SYNC_CRON = '20 9 * * 1'")
    expect(strip).toContain('Run Instagram Insights now — manual')
    expect(strip).toContain('Weekly Instagram Insights auto-run')
    expect(strip).toContain('value={formatMetric(instagramSnapshot?.metrics.followers)}')
    expect(strip).toContain("label={instagramShowViews ? 'Views' : 'Monthly growth'}")
    expect(strip).not.toContain('?? instagramHistory.at(-1)?.followerDelta')
    expect(strip).toContain('ariaLabel="Open Instagram Pulse analysis"')
    expect(strip).toContain('trendMode="bars"')
    expect(strip).toContain('instagramNetTrend.at(-1) ?? instagramSnapshot?.metrics.followerDelta')
    expect(strip).toContain('signedTrend')
    expect(strip).toContain('buildArtistSpotifyMonthlyStreams(spotifySnapshot)')
    expect(strip).toContain('buildArtistSpotifyMonthlyListeners(spotifySnapshot)')
    expect(source).toContain('const recent = values.slice(-12)')
    expect(source).toContain("const showTrend = trendMode === 'bars' ? trend.length >= 1 : trend.length >= 2")
    expect(spotifyDetails).toContain('useState<SpotifyPulseMetric>')
    expect(spotifyDetails).toContain('spotifyPulseMetricOptions(snapshot?.dataSource)')
    expect(spotifyDetails).toContain('fixedDomain={metric === \'popularity\' ? { min: 0, max: 100 } : undefined}')
    expect(spotifyDetails).toContain('detailFormatter={formatPulseExactMetric}')
    expect(spotifyDetails).toContain('label="Spotify chart metric"')
    expect(spotifyDetails).toContain("label={activeHasMonthly ? `Monthly ${metric}`")
    expect(spotifyDetails).toContain('title="Monthly breakdown"')
    expect(spotifyDetails).toContain('title="Top tracks"')
    expect(spotifyDetails).toContain('defaultOpen')
    expect(details).toContain("useState<'followers' | 'growth' | 'views'>('followers')")
    expect(details).toContain('title="Instagram Pulse"')
    expect(details).toContain("{ label: 'Views', value: snapshot?.metrics.views }")
    expect(details).toContain("typeof item.value === 'number' && Number.isFinite(item.value)")
    expect(details).toContain('label="Instagram chart metric"')
    expect(details).toContain("mode={activeMetric === 'growth' ? 'bars' : 'line'}")
    expect(details).toContain('selectPulseGrowthSeries(growthPoints, historyGrowthPoints, currentGrowthPoint)')
    expect(details).toContain('formatPulseExactMetric(point.followers)')
    expect(details).toContain('title="Monthly follower breakdown"')
    expect(details).toContain('monthlyFollowers.slice().reverse()')
    expect(source).toContain('function PulseTrendCard')
    expect(source).toContain('function PulseChart')
    expect(source).toContain('buildPulseChartDomain(recent.map((point) => point.value)')
    expect(source).toContain('function PulseDisclosureSection')
    expect(source).toContain('group-open:rotate-180')
    expect(source).toContain("value >= 0 ? 'bottom-1/2 bg-[#f97316]/90' : 'top-1/2 bg-red-300/75'")
    expect(source).not.toContain('Artist Kit / Finals')
  })
})
