import { afterEach, expect, spyOn, test } from 'bun:test';
import { randomBytes, randomUUID } from 'node:crypto';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DurableJournal, type DurableClaim } from '../../../shared/src/durable-execution/index.ts';
import { DurableReadRunner, type DurableReadBinding, type DurableReadInput } from './durable-read-runner.ts';
import { DurableChildRunner, durableChildRunId, validateDurableChildSchema, type DurableChildRequest } from './durable-child-runner.ts';
const cleanup: Array<() => void | Promise<void>> = [];
afterEach(async () => { for (const fn of cleanup.splice(0).reverse()) await fn(); });
async function fixture(costPolicy: DurableReadInput['costPolicy'] = {unit:'verified-free',maxTotalUnits:0,maxUnitsPerAttempt:0}) {
  const root=mkdtempSync(join(tmpdir(),'durable-child-')),key=randomBytes(32);cleanup.push(()=>rmSync(root,{recursive:true,force:true}));writeFileSync(join(root,'notes.txt'),'release notes');
  let journal=new DurableJournal({configRoot:root,key}),claim:DurableClaim|undefined,executions=0,reads=0,output='{"summary":"read"}';
  const binding:DurableReadBinding={credentialIdentity:'a'.repeat(64),workspace:{id:'w',name:'test',slug:'test',rootPath:root,createdAt:1},context:{provider:'pi',resolvedModel:'m',authType:'api_key',capabilities:{needsHttpPoolServer:false},connection:{slug:'local',name:'local',providerType:'pi',authType:'api_key',piAuthProvider:'openai',createdAt:1}}};
  const makeRunner=()=>new DurableReadRunner({journal,hostRuntime:{appRootPath:root,isPackaged:false},resolveBinding:()=>binding,authorizeRun:()=>{},authorizeTool:async()=>({principalId:'alice',credentialIdentity:binding.credentialIdentity,policyRevision:'p',allowed:true,requiresApproval:false,approvalExpiresAt:Date.now()+60000}),createBackend:args=>({async *chat(){
    executions++;const bridge=args.coreConfig.durableExecution!;
    const model=await bridge.checkpoint({kind:'model-start',turn:0,context:{messages:[]}});
    if(model.cached===undefined)await bridge.checkpoint({kind:'model-result',turn:0,message:{role:'assistant',stopReason:'toolUse',content:[{type:'toolCall',id:'read',name:'read',arguments:{path:'notes.txt'}}]}});
    const tool=await bridge.checkpoint({kind:'tool-start',turn:0,callId:'read',tool:'read',input:{path:join(root,'notes.txt')}});
    if(tool.cached===undefined){reads++;await bridge.checkpoint({kind:'tool-result',turn:0,callId:'read',result:readFileSync(join(root,'notes.txt'),'utf8')});}
    const final=await bridge.checkpoint({kind:'model-start',turn:1,context:{messages:['read']}});
    if(final.cached===undefined)await bridge.checkpoint({kind:'model-result',turn:1,message:{role:'assistant',stopReason:'stop',content:[{type:'text',text:output}]}});
    await bridge.checkpoint({kind:'complete'});
  },async abort(){},destroy(){}})});
  let runner=makeRunner();const seed:DurableReadInput={runId:randomUUID(),commandId:'seed',workspaceId:'w',connectionSlug:'local',model:'m',prompt:'parent',systemPrompt:'Read only',allowedTools:['read'],maxOutputTokens:128,deadlineAt:Date.now()+60000,maxModelAttempts:10,costPolicy,approvalPrincipalId:'alice'};
  const completed=await runner.start(seed),parentId=randomUUID();journal.admit({...completed.spec,runId:parentId,commandId:'parent'});claim=journal.claim(parentId,'w');executions=0;reads=0;
  cleanup.push(async()=>{await runner.quiesce();if(claim)journal.release(claim);journal.close()});
  const request:DurableChildRequest={slotId:'research',mode:'required',prompt:'Read notes',systemPrompt:'Read only',allowedTools:['read'],maxOutputTokens:64,maxModelAttempts:2,deadlineAt:seed.deadlineAt,costPolicy:seed.costPolicy,outputSchema:{type:'object',required:['summary'],properties:{summary:{type:'string'}}}};
  return {get journal(){return journal},get claim(){return claim!},get coordinator(){return new DurableChildRunner({journal,runner})},request,parentId,executions:()=>executions,reads:()=>reads,setOutput(value:string){output=value},async reopen(){if(claim){journal.release(claim);claim=undefined}await runner.quiesce();journal.close();journal=new DurableJournal({configRoot:root,key});runner=makeRunner();claim=journal.claim(parentId,'w')},async completeParent(){const bridge=journal.bridge(claim!);await bridge.checkpoint({kind:'model-start',turn:0,context:{}});await bridge.checkpoint({kind:'model-result',turn:0,message:{role:'assistant',stopReason:'stop',content:[{type:'text',text:'parent done'}]}});return bridge.checkpoint({kind:'complete'})}};
}
test('child uses stable identity and real read-runner checkpoints; repeated join never reruns',async()=>{const f=await fixture();const first=await f.coordinator.start(f.claim,f.request);expect(first.status).toBe('joined');expect(first.output).toEqual({summary:'read'});expect(f.reads()).toBe(1);expect(await f.coordinator.start(f.claim,f.request)).toEqual(first);expect(f.executions()).toBe(1);expect(first.childRunId).toBe(durableChildRunId('w',f.parentId,'research'));await f.completeParent();});
test('restart after child completion before join reuses committed child output',async()=>{const f=await fixture();const join=spyOn(f.journal,'joinChild').mockImplementation(()=>{throw new Error('lost join callback')});try{await expect(f.coordinator.start(f.claim,f.request)).rejects.toThrow('lost join callback')}finally{join.mockRestore()}expect(f.reads()).toBe(1);await f.reopen();expect((await f.coordinator.start(f.claim,f.request)).output).toEqual({summary:'read'});expect(f.executions()).toBe(1);expect(f.reads()).toBe(1);});
test('invalid required child output cannot join or complete its parent',async()=>{const f=await fixture();f.setOutput('{"wrong":true}');await expect(f.coordinator.start(f.claim,f.request)).rejects.toThrow('schema-validation-failed');await expect(f.completeParent()).rejects.toThrow('child');});
test('child constraints and frozen slot identity reject widening and divergence before execution',async()=>{const f=await fixture();await expect(f.coordinator.start(f.claim,{...f.request,maxOutputTokens:1000})).rejects.toThrow('child');expect(f.executions()).toBe(0);await f.coordinator.start(f.claim,f.request);await expect(f.coordinator.start(f.claim,{...f.request,prompt:'changed'})).rejects.toThrow();expect(f.executions()).toBe(1);});
test('unsupported schema semantics are rejected explicitly',()=>{expect(()=>validateDurableChildSchema({type:'object',additionalProperties:false})).toThrow('unsupported');expect(()=>validateDurableChildSchema({type:'object',required:['constructor']})).toThrow('unsupported');expect(()=>validateDurableChildSchema({type:'array',items:{type:'string',minLength:2}})).toThrow('unsupported');});
test('atomic child admission rollback leaves no orphan or root reservation',async()=>{const f=await fixture(),before=f.journal.get(f.parentId,'w'),rows=f.journal.listInternal('w').length;const original=(f.journal as any).save;const save=spyOn(f.journal as any,'save').mockImplementation((state:any,kind:string)=>{if(state.spec.runId===f.parentId&&kind==='child-admitted')throw new Error('parent commit unavailable');return original.call(f.journal,state,kind)});try{await expect(f.coordinator.start(f.claim,f.request)).rejects.toThrow('parent commit unavailable')}finally{save.mockRestore()}expect(f.journal.get(f.parentId,'w')).toEqual(before);expect(f.journal.listInternal('w')).toHaveLength(rows);expect(f.executions()).toBe(0);expect((await f.coordinator.start(f.claim,f.request)).status).toBe('joined');});
test('child attempt reservations cannot be multiplied by slots or recovered runs',async()=>{const f=await fixture();await f.coordinator.start(f.claim,{...f.request,maxModelAttempts:8});expect(f.journal.get(f.parentId,'w').childReservedModelAttempts).toBe(8);await f.reopen();await expect(f.coordinator.start(f.claim,{...f.request,slotId:'second',maxModelAttempts:3})).rejects.toThrow('budget-exhausted');expect(f.executions()).toBe(1);});
test('owned child cancellation propagates atomically while explicit detached children remain independent',async()=>{const f=await fixture();let finish!:(state:any)=>void;const pending=new Promise<any>(resolve=>finish=resolve);const coordinator=new DurableChildRunner({journal:f.journal,runner:{resume:()=>pending}});const required=coordinator.start(f.claim,f.request);void required.catch(()=>{});await coordinator.start(f.claim,{...f.request,slotId:'independent',mode:'detached'});const edges=f.journal.get(f.parentId,'w').children!;f.journal.command({runId:f.parentId,workspaceId:'w',commandId:'cancel-parent',expectedVersion:f.journal.get(f.parentId,'w').version,action:'cancel'});expect(f.journal.get(edges[0]!.childRunId,'w').status).toBe('cancelled');expect(f.journal.get(edges[1]!.childRunId,'w').status).toBe('running');finish(f.journal.get(edges[0]!.childRunId,'w'));await expect(required).rejects.toThrow('child-cancelled');});
test('one-level certification rejects descendants and direct child admission bypass',async()=>{const f=await fixture();await f.coordinator.start(f.claim,f.request);const child=f.journal.get(durableChildRunId('w',f.parentId,f.request.slotId),'w');expect(()=>f.journal.admit({...child.spec,runId:randomUUID(),commandId:'bypass'})).toThrow('atomic-admission-required');const childClaim={...f.claim,runId:child.spec.runId};await expect(f.coordinator.start(childClaim,{...f.request,slotId:'grandchild'})).rejects.toThrow();expect(f.executions()).toBe(1);});

test('root reserves the full child spending cap across siblings, not just first dispatch cost',async()=>{const f=await fixture({unit:'trusted-upper-bound',maxTotalUnits:4,maxUnitsPerAttempt:1});await f.coordinator.start(f.claim,{...f.request,costPolicy:{unit:'trusted-upper-bound',maxTotalUnits:2,maxUnitsPerAttempt:1}});expect(f.journal.get(f.parentId,'w').reservedUnits).toBe(2);await expect(f.coordinator.start(f.claim,{...f.request,slotId:'second',costPolicy:{unit:'trusted-upper-bound',maxTotalUnits:3,maxUnitsPerAttempt:1}})).rejects.toThrow('budget-exhausted');await expect(f.coordinator.start(f.claim,{...f.request,slotId:'zero',costPolicy:{unit:'trusted-upper-bound',maxTotalUnits:0,maxUnitsPerAttempt:0}})).rejects.toThrow('constraints-invalid');expect(f.executions()).toBe(1);});
test('joined acknowledgement remains available after parent completion without redispatch',async()=>{const f=await fixture();const joined=await f.coordinator.start(f.claim,f.request);await f.completeParent();expect(await f.coordinator.start(f.claim,f.request)).toEqual(joined);expect(f.executions()).toBe(1);});
test('required child cannot directly resume while its parent is paused',async()=>{const f=await fixture();const coordinator=new DurableChildRunner({journal:f.journal,runner:{resume:()=>new Promise(()=>{})}});void coordinator.start(f.claim,f.request);const childId=durableChildRunId('w',f.parentId,f.request.slotId);f.journal.command({runId:f.parentId,workspaceId:'w',commandId:'pause-parent',expectedVersion:f.journal.get(f.parentId,'w').version,action:'pause'});expect(f.journal.get(childId,'w').status).toBe('paused');expect(()=>f.journal.command({runId:childId,workspaceId:'w',commandId:'bypass',expectedVersion:f.journal.get(childId,'w').version,action:'resume'})).toThrow('parent-blocked');expect(()=>f.journal.claim(childId,'w')).toThrow();});
test('caller cannot rewrite a suspended parent claim to join across a newer control revision',async()=>{const f=await fixture();let finish!:(state:any)=>void;const coordinator=new DurableChildRunner({journal:f.journal,runner:{resume:()=>new Promise(resolve=>finish=resolve)}});const mutable={...f.claim};const running=coordinator.start(mutable,f.request);void running.catch(()=>{});const childId=durableChildRunId('w',f.parentId,f.request.slotId),childClaim=f.journal.claim(childId,'w'),bridge=f.journal.bridge(childClaim);await bridge.checkpoint({kind:'model-start',turn:0,context:{}});await bridge.checkpoint({kind:'model-result',turn:0,message:{role:'assistant',stopReason:'stop',content:[{type:'text',text:'{"summary":"done"}'}]}});await bridge.checkpoint({kind:'complete'});f.journal.release(childClaim);for(const action of ['pause','resume'] as const)f.journal.command({runId:f.parentId,workspaceId:'w',commandId:action,expectedVersion:f.journal.get(f.parentId,'w').version,action});mutable.controlRevision=f.journal.get(f.parentId,'w').controlRevision;finish(f.journal.get(childId,'w'));await expect(running).rejects.toThrow('dispatch-blocked');expect(f.journal.get(f.parentId,'w').children![0]!.status).toBe('admitted');});

test('required joins follow recorded slot order even when a later child finishes first',async()=>{const f=await fixture();let finish!:(state:any)=>void;const firstCoordinator=new DurableChildRunner({journal:f.journal,runner:{resume:()=>new Promise(resolve=>finish=resolve)}});const first=firstCoordinator.start(f.claim,f.request);await expect(f.coordinator.start(f.claim,{...f.request,slotId:'later'})).rejects.toThrow('join-order');expect(f.reads()).toBe(1);const id=durableChildRunId('w',f.parentId,f.request.slotId),claim=f.journal.claim(id,'w'),bridge=f.journal.bridge(claim);await bridge.checkpoint({kind:'model-start',turn:0,context:{}});await bridge.checkpoint({kind:'model-result',turn:0,message:{role:'assistant',stopReason:'stop',content:[{type:'text',text:'{"summary":"first"}'}]}});await bridge.checkpoint({kind:'complete'});f.journal.release(claim);finish(f.journal.get(id,'w'));expect((await first).output).toEqual({summary:'first'});expect((await f.coordinator.start(f.claim,{...f.request,slotId:'later'})).status).toBe('joined');expect(f.reads()).toBe(1);expect(f.journal.get(f.parentId,'w').children!.map(edge=>edge.slotId)).toEqual(['research','later']);});
test('a live child claim cannot admit a grandchild',async()=>{const f=await fixture();const coordinator=new DurableChildRunner({journal:f.journal,runner:{resume:()=>new Promise(()=>{})}});void coordinator.start(f.claim,f.request);const id=durableChildRunId('w',f.parentId,f.request.slotId),claim=f.journal.claim(id,'w');try{await expect(coordinator.start(claim,{...f.request,slotId:'grandchild'})).rejects.toThrow('depth-exceeded')}finally{f.journal.release(claim)}expect(f.journal.listInternal('w')).toHaveLength(3);});
