import { afterEach, expect, test } from 'bun:test'
import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { tmpdir } from 'node:os'
import { createBuildProvenance, isBuildInput, publishRendererBuild } from './build-provenance'

const roots: string[] = []
afterEach(() => { for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true }) })
function fixture() { const root = mkdtempSync(join(tmpdir(), 'build-provenance-')); roots.push(root); return root }
function write(root: string, path: string, value: string) { const file = join(root, path); mkdirSync(dirname(file), { recursive: true }); writeFileSync(file, value) }
function git(root: string, ...args: string[]) { return execFileSync('git', ['-C', root, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim() }

test('fingerprint uses current tracked and new source bytes, deletions and component-independent identity', () => {
  const root = fixture()
  git(root, 'init', '-q')
  write(root, 'apps/electron/src/main.ts', 'original')
  write(root, 'vendor/library/dist/index.js', 'vendored input')
  git(root, 'add', '.')
  git(root, '-c', 'user.name=Build Test', '-c', 'user.email=build-test@example.invalid', 'commit', '-qm', 'fixture')
  const info = () => createBuildProvenance({ rootDir: root, component: 'main', product: 'artist-os', now: new Date('2026-09-10T12:00:00Z') })
  const initial = info()
  expect(initial.commit).toBe(git(root, 'rev-parse', 'HEAD'))
  expect(initial.dirty).toBe(false)
  expect(initial.builtAt).toBe('2026-09-10T12:00:00.000Z')
  expect(initial.product).toBe('artist-os')
  expect(createBuildProvenance({ rootDir: root, component: 'renderer' }).sourceHash).toBe(initial.sourceHash)
  write(root, 'apps/electron/src/main.ts', 'modified')
  expect(info().sourceHash).not.toBe(initial.sourceHash)
  expect(info().dirty).toBe(true)
  write(root, 'apps/electron/src/main.ts', 'original')
  expect(info().sourceHash).toBe(initial.sourceHash)
  write(root, 'packages/new/src/feature.ts', 'untracked code')
  const added = info().sourceHash
  expect(added).not.toBe(initial.sourceHash)
  write(root, 'packages/new/src/feature.ts', 'modified untracked code')
  expect(info().sourceHash).not.toBe(added)
  rmSync(join(root, 'packages'), { recursive: true })
  rmSync(join(root, 'vendor/library/dist/index.js'))
  expect(info().sourceHash).not.toBe(initial.sourceHash)
})

test('env credentials dependencies and outputs do not enter fingerprint; credential implementation does', () => {
  const root = fixture(); git(root, 'init', '-q')
  write(root, 'packages/shared/src/credentials/manager.ts', 'credential implementation')
  const info = () => createBuildProvenance({ rootDir: root, component: 'preload' })
  const before = info()
  expect(before.commit).toBeNull()
  for (const path of ['.env', 'apps/electron/.env.local', 'packages/credentials.json', 'apps/key.pem', 'node_modules/pkg/index.js', 'apps/electron/dist/renderer/index.html', 'apps/electron/release-artist-os/app.dmg']) write(root, path, 'excluded private or generated bytes')
  expect(info().sourceHash).toBe(before.sourceHash)
  expect(isBuildInput('packages/shared/src/credentials/manager.ts')).toBe(true)
  write(root, 'packages/shared/src/credentials/manager.ts', 'changed implementation')
  expect(info().sourceHash).not.toBe(before.sourceHash)
  const credentialChange = info().sourceHash
  write(root, 'packages/shared/src/release-kit/storage.ts', 'release canon implementation')
  expect(info().sourceHash).not.toBe(credentialChange)
  const beforePatch = info().sourceHash
  write(root, 'patches/dependency.patch', 'patched dependency implementation')
  expect(info().sourceHash).not.toBe(beforePatch)
  const releaseAdded = info().sourceHash
  write(root, 'packages/shared/src/release-kit/storage.ts', 'updated release canon')
  expect(info().sourceHash).not.toBe(releaseAdded)
})

test('complete renderer publication replaces output and removes prior build', () => {
  const root = fixture(), destination = join(root, 'renderer'), staged = join(root, 'staged')
  write(destination, 'index.html', 'old'); write(destination, 'old.js', 'old chunk')
  write(staged, 'index.html', 'new'); write(staged, 'new.js', 'new chunk')
  publishRendererBuild(staged, destination)
  expect(readFileSync(join(destination, 'index.html'), 'utf8')).toBe('new')
  expect(existsSync(join(destination, 'new.js'))).toBe(true)
  expect(existsSync(join(destination, 'old.js'))).toBe(false)
  expect(existsSync(staged)).toBe(false)
})

test('incomplete build and failed publishing rename preserve exact previous renderer', () => {
  const root = fixture(), destination = join(root, 'renderer'), staged = join(root, 'staged')
  write(destination, 'index.html', 'old'); write(destination, 'old.js', 'old chunk')
  expect(() => publishRendererBuild(staged, destination)).toThrow('no index.html')
  write(staged, 'index.html', 'new')
  expect(() => publishRendererBuild(staged, destination, {
    exists: existsSync,
    remove: rmSync,
    rename: (from, to) => { if (String(from) === staged) throw new Error('injected publish failure'); renameSync(from, to) },
  })).toThrow('injected publish failure')
  expect(readFileSync(join(destination, 'index.html'), 'utf8')).toBe('old')
  expect(readFileSync(join(destination, 'old.js'), 'utf8')).toBe('old chunk')
})
