#!/usr/bin/env bun
import { importJWK, type JWK } from 'jose';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(import.meta.dir, '..');
const raw = process.env.ARTIST_OS_ENTITLEMENT_VERIFICATION_KEYS_JSON;
const currentKeyId = process.env.ARTIST_OS_ENTITLEMENT_KEY_ID_CURRENT;
if (!raw?.trim() || !currentKeyId?.trim()) fail('Missing Artist OS entitlement public-key release authority.');

let parsed: unknown;
try { parsed = JSON.parse(raw); } catch { fail('Artist OS entitlement verification keyring is not valid JSON.'); }
if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) fail('Artist OS entitlement verification keyring must be an object.');
const entries = Object.entries(parsed as Record<string, JWK>);
if (entries.length === 0 || !Object.prototype.hasOwnProperty.call(parsed, currentKeyId)) fail('Current Artist OS entitlement public key is missing.');

for (const [keyId, jwk] of entries) {
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/.test(keyId)
    || Object.keys(jwk).sort().join(',') !== 'crv,kty,x'
    || jwk.kty !== 'OKP' || jwk.crv !== 'Ed25519' || typeof jwk.x !== 'string') {
    fail('Artist OS entitlement keyring contains an invalid public Ed25519 JWK.');
  }
  await importJWK(jwk, 'EdDSA');
}

const destination = join(root, 'apps', 'electron', 'src', 'main', 'licensing', 'public-keyring.ts');
const serialized = JSON.stringify(Object.fromEntries(entries), null, 2);
writeFileSync(destination, `import type { ArtistOSEntitlementKeyring } from '@craft-agent/server-core/licensing';\n\n`
  + `// Generated by scripts/generate-artist-os-entitlement-public-keyring.ts. Public verification keys only.\n`
  + `export const ARTIST_OS_DESKTOP_ENTITLEMENT_KEYRING: ArtistOSEntitlementKeyring = Object.freeze(${serialized});\n`);
console.log(`Artist OS entitlement public keyring prepared (${entries.length} keys).`);

function fail(message: string): never {
  console.error(`RELEASE BLOCKED: ${message}`);
  process.exit(1);
}
