#!/usr/bin/env bun
import { chmodSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(import.meta.dir, '..');
const authorityPath = join(root, 'packages', 'entitlement-service', '.dev.vars');
const publicKeyringPath = join(root, 'apps', 'electron', 'src', 'main', 'licensing', 'public-keyring.ts');
const keyId = process.argv[2];

if (!keyId || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/.test(keyId)) {
  throw new Error('Provide a valid replacement key ID.');
}

const authority = readFileSync(authorityPath, 'utf8');
const generated = await crypto.subtle.generateKey({ name: 'Ed25519' }, true, ['sign', 'verify']);
const privateDer = new Uint8Array(await crypto.subtle.exportKey('pkcs8', generated.privateKey));
const publicJwk = await crypto.subtle.exportKey('jwk', generated.publicKey);
const privatePem = `-----BEGIN PRIVATE KEY-----\n${wrapBase64(Buffer.from(privateDer).toString('base64'))}\n-----END PRIVATE KEY-----`;
const publicKeyring = { [keyId]: { kty: publicJwk.kty, crv: publicJwk.crv, x: publicJwk.x } };

const updated = authority
  .replace(/^ARTIST_OS_ENTITLEMENT_KEY_ID_CURRENT=.*$/m, `ARTIST_OS_ENTITLEMENT_KEY_ID_CURRENT='${keyId}'`)
  .replace(
    /^ARTIST_OS_ENTITLEMENT_SIGNING_KEY_CURRENT='-----BEGIN PRIVATE KEY-----[\s\S]*?-----END PRIVATE KEY-----'$/m,
    `ARTIST_OS_ENTITLEMENT_SIGNING_KEY_CURRENT='${privatePem}'`,
  )
  .replace(
    /^ARTIST_OS_ENTITLEMENT_VERIFICATION_KEYS_JSON=.*$/m,
    `ARTIST_OS_ENTITLEMENT_VERIFICATION_KEYS_JSON='${JSON.stringify(publicKeyring)}'`,
  );

if (updated === authority || updated.includes('ARTIST_OS_ENTITLEMENT_SIGNING_KEY_CURRENT=\'-----BEGIN PRIVATE KEY-----') === false) {
  throw new Error('Local entitlement authority format was not recognized.');
}

writeFileSync(authorityPath, updated, { mode: 0o600 });
chmodSync(authorityPath, 0o600);
writeFileSync(
  publicKeyringPath,
  `import type { ArtistOSEntitlementKeyring } from '@craft-agent/server-core/licensing';\n\n`
    + `// Generated by scripts/generate-artist-os-entitlement-public-keyring.ts. Public verification keys only.\n`
    + `export const ARTIST_OS_DESKTOP_ENTITLEMENT_KEYRING: ArtistOSEntitlementKeyring = Object.freeze(${JSON.stringify(publicKeyring, null, 2)});\n`,
);

console.log(`Artist OS entitlement authority rotated to ${keyId}.`);

function wrapBase64(value: string): string {
  return value.match(/.{1,64}/g)?.join('\n') ?? value;
}
