import type { ArtistOSEntitlementKeyring } from '@craft-agent/server-core/licensing';

// Generated by scripts/generate-artist-os-entitlement-public-keyring.ts. Public verification keys only.
export const ARTIST_OS_DESKTOP_ENTITLEMENT_KEYRING: ArtistOSEntitlementKeyring = Object.freeze({
  "artistos-v1-2026-08-r1": {
    "kty": "OKP",
    "crv": "Ed25519",
    "x": "_igf0T8fHdKCIlauhhMyylyVUlBIlECI6yYfc9cBEpo"
  }
});
